# Lesson 5

In [1]:
import numpy as np
from datascience import *

In [10]:
my_odds=np.arange(1,42,4)
my_odds

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41])

In [11]:
np.cumprod(my_odds)

array([         1,          5,         45,        585,       9945,
           208845,    5221125,  151412625,  701649329,  191221397,
       -749857315], dtype=int32)

Why is there a negative? Change to float or change to 64bit.

In [12]:
np.cumprod(my_odds,dtype="int64")

array([            1,             5,            45,           585,
                9945,        208845,       5221125,     151412625,
          4996616625,  184874815125, 7579867420125], dtype=int64)

In [13]:
np.cumprod(my_odds,dtype="float64")

array([1.00000000e+00, 5.00000000e+00, 4.50000000e+01, 5.85000000e+02,
       9.94500000e+03, 2.08845000e+05, 5.22112500e+06, 1.51412625e+08,
       4.99661662e+09, 1.84874815e+11, 7.57986742e+12])

In [14]:
my_odds=np.arange(1.,42,4)
my_odds

array([ 1.,  5.,  9., 13., 17., 21., 25., 29., 33., 37., 41.])

These are the three ways to fix the cum product problem. 

In [15]:
my_array=['Lindsey','Blanks','South Carolina','Blue']
my_array

['Lindsey', 'Blanks', 'South Carolina', 'Blue']

In [22]:
np.char.upper(my_array)

array(['LINDSEY', 'BLANKS', 'SOUTH CAROLINA', 'BLUE'], dtype='<U14')

In [23]:
np.char.count(my_array, "a")

array([0, 1, 2, 0])

In [28]:
np.char.

AttributeError: module 'numpy.core.defchararray' has no attribute 'itemsize'

In [29]:
np.cumsum(my_odds)

array([  1.,   6.,  15.,  28.,  45.,  66.,  91., 120., 153., 190., 231.])

In [30]:
np.log(my_odds)

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207])